Add tests for ember-console
stefanpenner/ember-console pull request #10
Opened 2017-07-02 21:10 UTC by kratiahuja

Fixes #1 

- [x] Refactored `ember console` so that fastboot API is into its own file. Will make it easier in future to extend `ember console` for other platforms.
- [x] Added basic test harness.

cc: @stefanpenner

2017-07-02 21:19 UTC, stefanpenner requested changes
Awesome!  Left one nit-pick, otherwise this looks great.

2017-07-02 21:19 UTC, stefanpenner commented on lib/utils/fastboot-console.js
> +      resolve({app, response, fastbootConsoleApi})
we can avoid the outer promise, but simply the pojo here:

```js
return { app, response, fastbootConsoleApi }
````

2017-07-02 21:19 UTC, stefanpenner commented on lib/utils/fastboot-console.js
> +      reject(error)
and then the reject can be avoided entirely

2017-07-02 21:20 UTC, kratiahuja commented
Just realized travis god isn't running new tests. Will update config of both gods in a while.

2017-07-13 04:20 UTC, kratiahuja commented
Sorry @stefanpenner haven't got time to work on this. I'll work on fixing this this weekend.

2017-07-30 21:30 UTC, kratiahuja commented on lib/utils/fastboot-console.js
> +      resolve({app, response, fastbootConsoleApi})
The reason why I want the outer promise and the rejection is, I want to extend ember-console to help user understand their fastboot error. I have some ideas that I want to iterate on in a later PR :)

2017-07-30 22:16 UTC, kratiahuja commented
@stefanpenner super sorry for the delay here. totally forgot about this.

Updated to make both gods happy. Also upgrade ember-cli version in the addon and setup appveyor to run tests as well.

2017-07-30 22:47 UTC, stefanpenner approved these changes

2017-07-30 22:48 UTC, merged

2017-07-30 22:48 UTC, stefanpenner commented
you rock!